# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\DialogAbout.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogAbout(object):
    def setupUi(self, DialogAbout):
        DialogAbout.setObjectName("DialogAbout")
        DialogAbout.setWindowModality(QtCore.Qt.ApplicationModal)
        DialogAbout.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/OptiTool-Icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogAbout.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogAbout)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.lblEmpress = QtWidgets.QLabel(DialogAbout)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lblEmpress.setFont(font)
        self.lblEmpress.setAlignment(QtCore.Qt.AlignCenter)
        self.lblEmpress.setObjectName("lblEmpress")
        self.verticalLayout.addWidget(self.lblEmpress)
        self.lblCompany = QtWidgets.QLabel(DialogAbout)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblCompany.setFont(font)
        self.lblCompany.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCompany.setObjectName("lblCompany")
        self.verticalLayout.addWidget(self.lblCompany)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 15, -1, 15)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblVersion = QtWidgets.QLabel(DialogAbout)
        self.lblVersion.setAlignment(QtCore.Qt.AlignCenter)
        self.lblVersion.setObjectName("lblVersion")
        self.verticalLayout_2.addWidget(self.lblVersion)
        self.lblCreatedBy = QtWidgets.QLabel(DialogAbout)
        self.lblCreatedBy.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCreatedBy.setObjectName("lblCreatedBy")
        self.verticalLayout_2.addWidget(self.lblCreatedBy)
        self.lblDisclaimer = QtWidgets.QLabel(DialogAbout)
        self.lblDisclaimer.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDisclaimer.setObjectName("lblDisclaimer")
        self.verticalLayout_2.addWidget(self.lblDisclaimer)
        self.lblDate = QtWidgets.QLabel(DialogAbout)
        self.lblDate.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDate.setObjectName("lblDate")
        self.verticalLayout_2.addWidget(self.lblDate)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(DialogAbout)
        QtCore.QMetaObject.connectSlotsByName(DialogAbout)

    def retranslateUi(self, DialogAbout):
        _translate = QtCore.QCoreApplication.translate
        DialogAbout.setWindowTitle(_translate("DialogAbout", "Acerca de OptiTools"))
        self.lblEmpress.setText(_translate("DialogAbout", "OptiTools"))
        self.lblCompany.setText(_translate("DialogAbout", "BucketOfCode"))
        self.lblVersion.setText(_translate("DialogAbout", "Versión: "))
        self.lblCreatedBy.setText(_translate("DialogAbout", "Creado por: "))
        self.lblDisclaimer.setText(_translate("DialogAbout", "Todos los derechos reservados por OptiCortes."))
        self.lblDate.setText(_translate("DialogAbout", "2020 - 2021"))
