#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.9

pipelines:
  default:
    - parallel:
      - step:
          name: Install libs
          caches:
            - pip
          script:
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - pip install pytest
            - pytest -v tests/* --junitxml=test-reports/report.xml
      - step:
          name: Lint code
          script:
            # Enforce style consistency across Python projects https://flake8.pycqa.org/en/latest/manpage.html
            - pip install flake8
            - flake8 . --extend-exclude=dist,build --show-source --statistics
  
    - step:
        name: Build app
        deployment: production
        # trigger: manual  # Uncomment to make this a manual deployment.
        script:
          - pyinstaller -y --clean --name OptiTools --noconsole --icon ./imgs/OptiTool-Icon.ico ./AppGraphic.py